name: tutorial
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager: ^0.4.5+14
  shared_preferences: ^0.5.10
  audioplayers: ^0.16.1
  foreground_service: ^2.0.1+1
  android_intent: ^0.3.7+4
  intl: ^0.16.1
  flutter_phoenix: ^0.1.0
  weather: ^1.2.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
